# Generated by Django 6.0 on 2025-12-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='latitude',
            field=models.FloatField(default=20.5937),
        ),
        migrations.AddField(
            model_name='doctor',
            name='longitude',
            field=models.FloatField(default=78.9629),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
